### ISSUE TITLE
Friend using TextSecure gets olg version key request

### ISSUE THREAD

**Issue by matlink** [SecuredText/SecuredText#14] opened 2015-03-22 19:53 UTC
I've just installed SecuredText and tried to initiate a new connexion with a friend who still uses TextSecure by sending new secured connexion. It sends a new key request but he gets this error message : 
> Received a message ecrypted using an old version of TextSecure that is no longer supported. Please ask the sender to upgrade to the most recent version and resend the message

I've build the apk from sources on github.

**Comment by johanw666** [comment] 2015-03-22 19:57
Your friend is using TextSecure 2.7.x which does not support encrypted sms/mms anymore. Have him downgrade to 2.6.4 or install SecuredText alongside TextSecure.

**Comment by pR0Ps** [comment] 2015-03-22 19:59
@johanw666 is correct, closing.

**Closed by pR0Ps** 2015-03-22 19:59 UTC
Labels: wontfix

**Comment by matlink** [comment] 2015-03-22 20:00
Well I can send him encrypted messages to him with TextSecure, so he DOES support ecrypted sms/mms. Reopening.

**Comment by pR0Ps** [comment] 2015-03-22 20:10
The "Received a message encrypted using an old version of TextSecure that is no longer supported. Please ask the sender to upgrade to the most recent version and resend the message" message TextSecure is from a 2.7.0+ version that doesn't support SMS anymore, just push.

You are likely sending him an encrypted message using push with TextSecure which is why it's going through.

Since SecuredText doesn't support push, it sends an SMS, which is rejected by TextSecure, which shows that message.

**Comment by BastienLQ** [comment] 2015-03-22 21:01
No, it this message is sent because of an old version of TextSecure. See 0574ec170a2743baa140e887400fa4c0f2b26d04. So this is not a bug; your friend just need to upgrade to TextSecure <= 2.6.4 or to SecuredText.
